import IISInformacionnayaSistemaInvestmentEController from '../i-i-s-informacionnaya-sistema-investment-e';

var IISInformacionnayaSistemaInvestmentENewController = IISInformacionnayaSistemaInvestmentEController;
export default IISInformacionnayaSistemaInvestmentENewController;
