import IISInformacionnaya_sistemaInvestmentEController from '../i-i-s-informacionnaya-sistema-investment-e';

var IISInformacionnaya_sistemaInvestmentENewController = IISInformacionnaya_sistemaInvestmentEController;
export default IISInformacionnaya_sistemaInvestmentENewController;
