import IISInformacionnayaSistemaSubindustryEController from '../i-i-s-informacionnaya-sistema-subindustry-e';

var IISInformacionnayaSistemaSubindustryENewController = IISInformacionnayaSistemaSubindustryEController;
export default IISInformacionnayaSistemaSubindustryENewController;
