import IISInformacionnayaSistemaComponentEController from '../i-i-s-informacionnaya-sistema-component-e';

var IISInformacionnayaSistemaComponentENewController = IISInformacionnayaSistemaComponentEController;
export default IISInformacionnayaSistemaComponentENewController;
